app/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

from .sitemaps import StaticSitemap

sitemaps = {
    # 'help': HelpSitemap,
    # 'need_help':NeedHelpSitemap,
    'static':StaticSitemap
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path(
    "robots.txt",
    TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
]

app/main/urls.py
from django.urls import path
from .views import index, mapview,banks, need_help, help, help_list, need_help_list, thanks, google

urlpatterns = [
    path("", index, name="index" ),
    path("map/", mapview, name="map"),
    path("help/", help, name="help" ),
    path("need_help/", need_help, name="need_help" ),
    path("help_list/", help_list, name="help_list" ),
    path("need_help_list/", need_help_list, name="need_help_list" ),
    path("banks/", banks, name="banks"),

    path("thanks/", thanks, name="thanks"),

    path("google266444e0b9cd4821.html", google, name="google")

]

app/main/models.py
# from pyexpat import model
from django.db import models

class Help(models.Model):
    title = models.CharField(max_length=20, db_column="title")
    name = models.CharField(max_length=255)
    tel = models.CharField(max_length=15)
    details = models.TextField(max_length=1000)
    # pub_date = models.DateTimeField(auto_now_add=True)
    mod_date = models.DateTimeField(auto_now=True)
    link = models.URLField(max_length=1000, blank=True)

    class Adress(models.TextChoices):
        chisinau = "chisinau", "chisinau"
        balti = "balti", "balti"
        comrat = "comrat", "comrat"
        anenii_noi = "anenii_noi", "anenii_noi"
        basarabeasca = "basarabeasca", "basarabeasca"
        briceni = "briceni", "briceni"
        cahul = "cahul", "cahul"
        cantemir = "cantemir", "cantemir"
        calarasi = "calarasi", "calarasi"
        causeni = "causeni", "causeni"
        cimislia = "cimislia", "cimislia"
        criuleni = "criuleni", "criuleni"
        donduseni = "donduseni", "donduseni"
        drochia = "drochia", "drochia"
        dubasari = "dubasari", "dubasari"
        edinet = "edinet", "edinet"
        falesti = "falesti", "falesti"
        floresti = "floresti", "floresti"
        glodeni = "glodeni", "glodeni"
        hincesti = "hincesti", "hincesti"
        ialoveni = "ialoveni", "ialoveni"
        leova = "leova", "leova"
        nisporeni = "nisporeni", "nisporeni"
        ocnita = "ocnita", "ocnita"
        orhei = "orhei", "orhei"
        rezina = "rezina", "rezina"
        riscani = "riscani", "riscani"
        singerei = "singerei", "singerei"
        soroca = "soroca", "soroca"
        straseni = "straseni", "straseni"
        soldanesti = "soldanesti", "soldanesti"
        stefan_voda = "stefan_voda", "stefan_voda"
        taraclia = "taraclia", "taraclia"
        telenesti = "telenesti", "telenesti"
        ungheni = "ungheni", "ungheni"
    
    address = models.CharField(max_length=1000, choices=Adress.choices, default="chisinau")
    valabil = models.BooleanField(default=True)
    
    class Category(models.TextChoices):
        cazare = "cazare", 'Cazare | Проживання'
        transport = "transport", 'Transport | Транспорт'
        consiliere = "consiliere", 'Consiliere | Консультування'
        voluntariat = 'voluntariat', 'Волонтерство, переклад'
        donatii = 'donatii', 'Haine, alimente | Одяг, їжа'
        lucru = 'lucru', 'Lucru | Работа '
        medical = 'medical', 'Servicii medicale | Медицинские услуги'
    
    category = models.CharField(max_length=20, choices=Category.choices, null=True, default="None")
    
    def __str__(self):
        return f"{self.title}"
    

class NeedHelp(models.Model):
    title = models.CharField(max_length=20,db_column="title")
    name = models.CharField(max_length=255)
    tel = models.CharField(max_length=15)
    details = models.TextField(max_length=1000)
    # pub_date = models.DateTimeField(auto_now_add=True)
    mod_date = models.DateTimeField(auto_now=True)
    link = models.URLField(max_length=1000, blank=True)
    valabil = models.BooleanField(default=True)
    
    class Category(models.TextChoices):
        cazare = "cazare", 'Cazare | Проживання'
        transport = "transport", 'Transport | Транспорт'
        consiliere = "consiliere", 'Consiliere | Консультування'
        voluntariat = 'voluntariat', 'Волонтерство, переклад'
        donatii = 'donatii', 'Haine, alimente | Одяг, їжа'
        lucru = 'lucru', 'Lucru | Работа '
    
    category = models.CharField(max_length=20, choices=Category.choices, null=True, default="None")
    
    def __str__(self):
        return f"{self.category}"
# Create your models here.

app/main/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Help, NeedHelp
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0")

def index(request):
    # help = Help.objects.order_by("mod_date")()
    # context = {
    #     "help": help,
    # }
    return render(request, "main/index.html")


def help(request):
    if request.method == "POST":
        # print(request.POST)
        help = Help.objects.create(
            title=request.POST.get("help_type"),
            name = request.POST.get("name"),
            tel = request.POST.get("tel"),
            details=request.POST.get("details"),
            link=request.POST.get("link"),
            address=request.POST.get("address"),
            category=request.POST.get('category'),
            author=request.POST.get('author')

        )
        return redirect('index')

    help = Help.objects.order_by("mod_date")
    context = {
        "help": help,
    }
    return render(request, "main/help.html", context=context)

def need_help(request):
    if request.method == "POST":
        help = NeedHelp.objects.create(
                title=request.POST.get("help_type"),
                name = request.POST.get("name"),
                tel = request.POST.get("tel"),
                details=request.POST.get("details"),
                link=request.POST.get("link"),
                category=request.POST.get('category')
            )
    help = NeedHelp.objects.order_by("mod_date")
    context = {
        "help": help,
    }
    return render(request, "main/need_help.html", context=context)




def mapview(request):
    help = Help.objects.order_by("mod_date")
    address = request.GET.get("address")
    if address:
        help = help.filter(address=address)
   
    paginator = Paginator(help, 6)

    page_number = request.GET.get('page', 1)

    try:
        help = paginator.page(page_number)
    except PageNotAnInteger:
        help = paginator.page(1)
    except EmptyPage:
        page_number = paginator.page(paginator.num_pages)
    
    page_obj = paginator.get_page(page_number)

    
    context = {
        "help": help,
        "page_obj": page_obj,
        "page_number": page_number,
        "address": address,
    }

    return render(request, "working.html", context=context)

def banks(request):
    return render(request, "main/bank_list.html")

def help_list(request):
    help_list = Help.objects.order_by("-pk")
    all_list = help_list
    
    help_type = request.GET.get("category")
    
    address = request.GET.get("address")

    author = request.GET.get("author")
    
    
    if address:
        help_list = help_list.filter(address=address)
    if help_type:
        help_list = help_list.filter(category=help_type)
    if author:
        help_list = help_list.filter(author=author)


    if help_list:
        paginator = Paginator(help_list, 21)
    else:
        paginator = Paginator(all_list, 21)
    
    page_number = request.GET.get('page', 1)
    
    try:
        help = paginator.page(page_number)
    except PageNotAnInteger:
        help = paginator.page(1)
    except EmptyPage:
        page_number = paginator.page(paginator.num_pages)
    
    page_obj = paginator.get_page(page_number)
    
    context = {
        "help": help,
        "page_obj": page_obj,
        "page_number": page_number,
        "help_list": help_list,
        "help_type": help_type,
        "address": address,

    }
    return render(request, "main/help_list.html", context=context)

def need_help_list(request):
    
    help_type = request.GET.get("help_type")
    
    help_list = NeedHelp.objects.order_by("-pk")
    all_list = help_list
    
    address = request.GET.get("address")

    if help_list:
        paginator = Paginator(help_list, 21)
    else:
        paginator = Paginator(all_list, 21)

    page_number = request.GET.get('page', 1)
    try:
        help = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = paginator.page(paginator.num_pages)
    page_obj = paginator.get_page(page_number)
    context = {
        "help": help,
        "page_obj": page_obj,
        "page_number": page_number,
        "help_list": help_list,
        "help_type": help_type,
        "address": address,

    }
    return render(request, "main/help_list.html", context=context)



def thanks(request):
    
    context = {

    }
    return render(request, "main/thanks.html", context=context)

def google(request):
    return render(request,"google266444e0b9cd4821.html")
# Create your views here.

app/main/templates/main/bank_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <meta proprety="og:image" content="{% static 'images/hrivne.jpg' %}"/>
  <meta proprety="og:image:url" content="{% static 'images/hrivne.jpg' %}"/>
  <meta proprety="og:image:alt" content="UA money"/>
  <meta property="og:image:type" content="image/jpg">
  <meta property="og:image:width" content="1024"/>
  <meta property="og:image:height" content="1024"/>
  <meta property="og:title" content="Вывод валюты с украинских счетов" />
  <meta property="og:url" content="https://help-ua.daoi-source.com/banks/" />
  <meta property="og:site_name" content="https://daoi-source.com/banks/" />
  <meta property="og:description" content="Банки Молдовы - ближе к украинскому народу" />
  <meta name="twitter:image" content="{% static 'images/hrivne.jpg' %}"/>
  <meta name="twitter:card" content="summary_large_image"/>
  <meta name="twitter:title" content="Вывод валюты с украинских счетов"/>
  <meta name="twitter:description" content="Банки Молдовы - ближе к украинскому народу"/>

{% endblock %}
{% block title %}
Вывод валюты с украинских счетов
{% endblock %}
{% block main %}
<h1 class="text-center" style="margin-top:3rem">Банки Молдовы - ближе к украинскому народу</h1>
<div class="container" style="margin-top:1.5rem;margin-bottom:5rem">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="card border-primary" style="width: 100%;min-height: 1250px;">
                <img src="{% static 'images/pcb.png' %}" class="card-img-top" alt="ProCredit Bank Moldova" style="padding: .75rem;"  >
                <div class="card-body">
                  <h5 class="card-title">ProCredit Bank Moldova</h5>
                  <p class="card-text">Зони самообслуговування ProCredit Bank доступні цілодобово. Поповнення банкоматів готівкою відбувається регулярно, в залежності від потреби.</p>
                  <p class="card-text">Умови обслуговування громадян України, що перебувають на території Республіки Молдова:
                    <ul>
                        <li> Власники карток VISA, емітованих українськими банками, мають можливість зняти готівку у доларах США і ЄВРО без комісії ProCredit Bank.</li>
                        <li> Денний ліміт на зняття готівки складає 400 ЄВРО на добу, або еквівалент у доларах США та молдавських леях.</li>
                        <li>Громадяни України можуть відкривати поточні рахунки в ProCredit Bank згідно діючого законодавства Республіки Молдова, без комісії за обслуговування.</li>
                        <li> Банк погоджує з державними установами й інші можливості надання допомоги громадянам України, які потребують підтримки.</li>
                        
                    </ul>
                    Також хочемо звернути Вашу увагу, що курс обміну валюти по банківських картках VISA чи Mastercard (при знятті чи оплаті) у ці дні більш вигідний, ніж обмін у валютній касі. Обмінний курс Ви можете перевірити на офиційному сайті операторів:
                    <ul>
                    <li><a href="https://usa.visa.com/support/consumer/travel-support/exchange-rate-calculator.html?fbclid=IwAR2aopAAchEYSc4qc0f6NnqOmzCukdCyuvOxS4YB9Sf7w1fdvPYNlwnvod8">VISA</a></li>
                    <li><a href="https://www.mastercard.us/en-us/personal/get-support/convert-currency.html?fbclid=IwAR2GZOEp4tsajH65RDeKrvM7T1jd6u4Y2pbuBW31trBrhx6dSbKkijqgpQM">Mastercard</a></li></ul>
                    За додатковою информацією дзвоніть<span>
                    <a class="btn btn-primary" href="tel:080000010">📞 0800 000 10</a></span></p>
                    <p class="card-text">З повагою,
                    Команда ProCredit Bank 🏦</p>
                  <a href="https://www.procreditbank.md/" class="btn btn-primary">Команда ProCredit Bank</a>
                </div>
              </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="card border-success d-flex flex-column align-items-between" style="width: 100%; min-height: 1250px;">
                <img src="https://newsmaker.md/wp-content/uploads/2022/02/fincombank.jpg" class="card-img-top" alt="FinComBank" style="max-height: 450px; width: auto;padding: .75rem;">
                <div class="card-body">
                  <h5 class="card-title">FinComBank: В знак солидарности отменены комиссия и лимит на снятие наличных с украинских карт</h5>
                  <p class="card-text">В условиях сложившейся ситуации, FinComBank выражает солидарность и поддержку гражданам Украины, которые находятся на территории Республики Молдова. В этой связи, был принят ряд мер, которые направлены на поддержку и помощь нашим украинским соседям, пересекающим границу.</p>
                    <p class="card-text">Чтобы поддержать всех, кто оказался в очень сложной ситуации, мы предоставляем возможность снимать наличные в банкоматах FinComBank с карт украинских банков без ограничений по сумме, и с комиссией ноль.  Деньги можно снять в национальной валюте, MDL, а также в иностранной валюте, EUR и USD. Также, нет никаких ограничений по количеству снятий в банкоматах Банка.</p>
                    <p class="card-text">Отдельно хотим обратить внимание, что несмотря на отмену комиссии и лимитов по сумме и количеству снятий с украинских карт в банкоматах FinComBank, в то же время могут иметь место ограничения со стороны банков эмитентов украинских карт. При этом сеть банкоматов FinComBank обслуживает карты украинских банков без каких-либо ограничений.</p>
                    <p class="card-text">Благодарим за оказанное доверие, и желаем всем мира и добра. Мы солидарны, мы рядом!</p>
                  <a href="#" class="btn btn-primary">FinComBank website</a>
                </div>
              </div>
        </div>
        <div class="col-md-6 col-sm-12" style="margin-top: 1rem;">
            <div class="card border-success d-flex flex-column align-items-between" style="width: 100%; min-height: 1250px;">
                <img src="https://www.maib.md/storage/media/2022/02/25//image_1645807721_Q6kvQYwT54.jpg" class="card-img-top" alt="FinComBank" style="max-height: 450px; width: auto;padding: .75rem;">
                <div class="card-body">
                  <h5 class="card-title">Maib: мы рядом</h5>
                  <p class="card-text">Maib готов оказать всю возможную поддержку гражданам Украины, которые сейчас находятся в Республике Молдова.</p>
                  <p class="card-text">В подтверждении этого мы отменяем комиссию за транзакции в банкоматах maib по снятию наличных cредств с карт, выпущенных украинскими банками. Таким образом, украинские граждане могут снимать в банкоматах maib молдавские леи, доллары и евро без оплаты комиссии maib (подчеркнём, что может применяться комиссия банка эмитента).</p>
                  <p class="card-text">Отметим, что стандартная комиссия за снятие наличных денег с карты иностранного банка составляет при снятии в леях: 1,5% + 20 леев и 2,5% + 1 USD/ 1 EUR при снятии в валюте.</p>
                  <p class="card-text">Кроме того, maib приступил к выпуску бесплатных карт в леях, долларах и евро для украинских граждан.</p>
                  <p class="card-text">Мгновенные карты в леях можно получить сразу при обращении в филиал maib. Именные Карты в иностранной валюте выдаются в течении 24 часов и могут быть отправлены на любой адрес - Бесплатно (карты не доставляются в регионы левобережья Днестра и мун. Бендеры).</p>
                  <p class="card-text">Для оформления банковской карты гражданин Украины должен иметь с собой заграничный паспорт Украины.</p>
                  <p class="card-text">Также отметим что в связи с большим количеством транзакций по снятию наличных денег в сети банкоматов maib был установлен дневной лимит в размере 100 долларов/100 евро на карту, выпущенную одним из украинских банков</p>
                  <a href="https://www.maib.md/ru/noutati/maib:-suntem-alaturi" class="btn btn-primary">MAIB website</a>
                </div>
              </div>
        </div>
        <div class="col-md-6 col-sm-12" style="margin-top: 1rem;">
            <div class="card border-primary d-flex flex-column align-items-between" style="width: 100%; min-height: 1250px;">
                <img src="https://constructdepo.md/wp-content/uploads/2020/10/victoriabank-logo-cu-endorsment-cmyk-fin01.jpg" class="card-img-top" alt="FinComBank" style="max-height: 450px; width: auto;padding: .75rem;">
                <div class="card-body">
                  <h5 class="card-title">Обмінний еквівалент 20 000 леїв (33766 UAH / 1000 євро) за офіційним курсом НБМ.</h5>
                  <p class="card-text">Victoriabank вживає невідкладні заходи для прийому громадян України, які прибули до Молдови. З сьогоднішнього дня ми запустили спеціальний продукт для будь-якого громадянина України, який за українським паспортом має можливість обміняти гривні на молдавські леї за курсом, встановленим Національним Банком Молдови. Максимальна сума, на яку приймається цей обмін, становить еквівалент 20 000 леїв (1000 євро) на людину.</p>
                  <p class="card-text">Шановні громадяни України, наші співробітники обслуговуватимуть Вас без необхідності стояти в черзі, достатньо мати з собою українське посвідчення особи і ви будете обслуговуватися в пріоритеті.</p>
                  <p class="card-text">Ми солідарні з людьми, які потребують нашої допомоги!</p>
                  <a href="https://www.victoriabank.md/en/" class="btn btn-primary">Victoriabank website</a>
                </div>
              </div>
        </div>
        
    </div>
</div>
{% endblock main %}

app/main/templates/main/help.html
{% extends 'base.html' %}

{% block main %}
<div class="container" style="margin: 3rem; max-width: 80vw;">
    <div class="row">
        <form method="post">
          {% csrf_token %} 
          <h1 class="text-center">Предлагайте помощь</h1>
          <br>
            <div class="form-group">
              <label for="help_type">Title</label>
              <input type="text" class="form-control" id="help_type" name="help_type" aria-describedby="Help Type" placeholder="Enter Your Help Type" maxlength="20" required>
            </div>
            <div class="form-group">
              <label for="category">Category</label>
              <select name="category" id="category" class="form-control" required>
                <option value="cazare">Cazare | Проживання</option>
                <option value="transport">Transport | Транспорт</option>
                <option value="consiliere">Consiliere | Консультування</option>
                <option value="voluntariat">Волонтерство, переклад</option>
                <option value="donatii">Haine, alimente | Одяг, їжа</option>
                <option value="lucru">Lucru | Работа</option>
                <option value="medical">Servicii medicale | Медицинские услуги</option>
              </select>
            </div>
            <div class="form-group">
              <label for="author">Author</label>
              <select name="author" id="author" class="form-control" required>
                <option value="fizica">Persoana Fizica | Физическое лицо</option>
                <option value="juridica">Persoana Juridica | Юридическое лицо</option>
              </select>
            </div>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" aria-describedby="name" placeholder="Enter Your Name" maxlength="255" required>
              </div>
              <div class="form-group">
                <label for="tel">Telephone number</label>
                <input type="text" class="form-control" id="tel" name="tel" aria-describedby="tel" placeholder="Enter your phone number" maxlength="15" required>
              </div>
              <div class="form-group">
                <label for="details">Details</label>
                <textarea type="text" class="form-control" id="details" name="details" aria-describedby="details" placeholder="Please enter details about your Help Offer" maxlength="1000" required></textarea>
              </div>
              <div class="form-group">
                <label for="link">Link</label>
                <input type="text" class="form-control" id="link" name="link" aria-describedby="link" placeholder="Paste your link here">
              </div>
              <div class="form-group">
                <label for="address">Please select the region</label>
                <select class="form-control" id="address" name="address">
                  <option value="chisinau">Chișinău</option>
                  <option value="balti">Balți</option>
                  <option value="comrat">Comrat</option>
                  <option value="anenii_noi">Anenii Noi</option>
                  <option value="basarabeasca">Basarabeasca</option>
                  <option value="briceni">Briceni</option>
                  <option value="cahul">Cahul</option>
                  <option value="cantemir">Cantemir</option>
                  <option value="calarasi">Călărași</option>
                  <option value="causeni">Căușeni</option>
                  <option value="cimislia">Cimișlia</option>
                  <option value="criuleni">Criuleni</option>
                  <option value="donduseni">Dondușeni</option>
                  <option value="drochia">Drochia</option>
                  <option value="dubasari">Dubăsari</option>
                  <option value="edinet">Edineț</option>
                  <option value="falesti">Fălești</option>
                  <option value="floresti">Florești</option>
                  <option value="glodeni">Glodeni</option>
                  <option value="hincesti">Hîncești</option>
                  <option value="ialoveni">Ialoveni</option>
                  <option value="leova">Leova</option>
                  <option value="nisporeni">Nisporeni</option>
                  <option value="ocnita">Ocnița</option>
                  <option value="orhei">Orhei</option>
                  <option value="rezina">Rezina</option>
                  <option value="riscani">Rîșcani</option>
                  <option value="singerei">Sîngerei</option>
                  <option value="soroca">Soroca</option>
                  <option value="straseni">Strășeni</option>
                  <option value="soldanesti">Șoldănești</option>
                  <option value="stefan_voda">Ștefan Vodă</option>
                  <option value="taraclia">Taraclia</option>
                  <option value="telenesti">Telenești</option>
                  <option value="ungheni">Ungheni</option>
                </select>
               </div>
              <br>
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
</div>
</div>
{% endblock %}

app/main/templates/main/help_list.html
{% extends 'base.html' %}
{% block title %}
Cнятие валюты с украинских счетов
{% endblock %}
{% block main %}
<br>
<div class="container">
<div class="container">
  <br>
  {% if request.path == "/help_list/" %}
  {% csrf_token %}
  <form method="get" class="row align-items-center justify-content-center">
    <h1 class="text-center">Список людей, готовых помочь</h1>
    <div class="form-group">
      <label for="category">Category</label>
      <select name="category" id="category" class="form-control">
        {% if help_type %}
        <option value="{{ help_type }}">{{help_type|upper}}</option>
        {% endif %}
        <option value="">All</option>
        <option value="cazare">Cazare | Проживання</option>
        <option value="transport">Transport | Транспорт</option>
        <option value="consiliere">Consiliere | Консультування</option>
        <option value="voluntariat">Волонтерство, переклад</option>
        <option value="donatii">Haine, alimente | Одяг, їжа</option>
        <option value="lucru">Lucru | Работа</option>
        <option value="medical">Servicii medicale | Медицинские услуги</option>
      </select>
    </div>
    <div class="form-group">
      <label for="author">Author</label>
        <select name="author" id="author" class="form-control" >
        <option value="">All</option>
        <option value="fizica">Persoana Fizica | Физическое лицо</option>
        <option value="juridica">Persoana Juridica | Юридическое лицо</option>
      </select> 
    </div>
    <div class="form-group">
        <label for="address">Please select the region</label>
        <select style="margin: .5rem;" class="form-control" id="address" name="address">
          {% if address %}
          <option disabled selected  value="">{{ address|upper }}</option>
          {% endif %}
          <option value="">All</option>
          <option value="chisinau">Chișinău</option>
          <option value="balti">Balți</option>
          <option value="comrat">Comrat</option>
          <option value="anenii_noi">Anenii Noi</option>
          <option value="basarabeasca">Basarabeasca</option>
          <option value="briceni">Briceni</option>
          <option value="cahul">Cahul</option>
          <option value="cantemir">Cantemir</option>
          <option value="calarasi">Călărași</option>
          <option value="causeni">Căușeni</option>
          <option value="cimislia">Cimișlia</option>
          <option value="criuleni">Criuleni</option>
          <option value="donduseni">Dondușeni</option>
          <option value="drochia">Drochia</option>
          <option value="dubasari">Dubăsari</option>
          <option value="edinet">Edineț</option>
          <option value="falesti">Fălești</option>
          <option value="floresti">Florești</option>
          <option value="glodeni">Glodeni</option>
          <option value="hincesti">Hîncești</option>
          <option value="ialoveni">Ialoveni</option>
          <option value="leova">Leova</option>
          <option value="nisporeni">Nisporeni</option>
          <option value="ocnita">Ocnița</option>
          <option value="orhei">Orhei</option>
          <option value="rezina">Rezina</option>
          <option value="riscani">Rîșcani</option>
          <option value="singerei">Sîngerei</option>
          <option value="soroca">Soroca</option>
          <option value="straseni">Strășeni</option>
          <option value="soldanesti">Șoldănești</option>
          <option value="stefan_voda">Ștefan Vodă</option>
          <option value="taraclia">Taraclia</option>
          <option value="telenesti">Telenești</option>
          <option value="ungheni">Ungheni</option>
        </select>
    </div>
        <input style="margin: .5rem;" type="submit" class="btn btn-primary" value="Поиск">
        <a href="{% url 'help' %}" class="btn btn-success">Предлагайте помощь</a>
       
    </form>
  {% else %}
    <div class="row align-items-center justify-content-center">
      <h1 class="text-center">Список людей, обращающихся за помощью</h1>
      <br>
      <a href="{% url 'need_help' %}" class="btn btn-success">Обратитесь за помощью</a>
    </div>
  {% endif %}
  </div>
  <br>
<div class="container">
    <div class="row">
      {% if not help_list %}
      <div class="alert alert-danger">
        Пока нет объявлений для данной области | все объявления перечислены
      </div>
      {% elif address %}
      <div class="alert alert-primary">
      Результаты поиска:
      </div>
      {% endif %}

{% for item in help %}
<div class="col-md-4 col-sm-12 d-flex justify-content-center">
    <div class="card d-flex justify-content-center align-items-between" style="width: 18rem; margin:.75rem 0rem;min-height:200px ;">
        <div class="card-body d-flex justify-content-center align-items-between flex-column">
          <h5 class="card-title">{{ item|upper }}</h5>
          <h6><span class="badge bg-primary">{{ item.get_category_display }}</span><span class="badge bg-success">{{ item.get_address_display }}</span></h6>
          <p class="card-text">{{ item.details }}</p>
          {% if item.mod_date%}
          <p class="card-text">{{ item.mod_date }}</p>
          {% elif item.pub_date %}
          <p class="card-text">{{ item.pub_date }}</p>
          {% else %}
          <p class="card-text">Feb. 25, 2022</p>
          {% endif %}
          <div class="position-relative bottom-0 d-flex align-items-end justify-content-center flex-column">
            {% if item.link %}
            <a href="{{ item.link }}" class="btn btn-secondary col-sm-12">Link</a>
            {% endif %}
            <a style="margin-top:.5rem" href="tel:{{ item.tel }}" class="btn btn-primary col-sm-12">{{ item.tel }}</a>
          </div>
        </div>
      </div>
</div>
{% endfor %}


</div>
</div>
</div>
{% if help.has_other_pages %}
                <div class="container-fluid">
                <div class="container-fluid" style="width: 100%">
                    <div class="col-sm-12 d-flex justify-content-center" style="margin:3rem 0rem;">
                          <ul class="pagination" style="padding: 0px 5rem">
                                {% if help.has_previous %}
                                <li class="page-item"><a class="page-link" href="?category={{ help_type }}&author={{ author }}&address={{ address }}&page={{ help.previous_page_number }}">Previous</a></li>
                                {% endif %}
                                <h3 style="margin:0px 10px;width:max-content;">{{ page_number }} of {{ help.paginator.num_pages }}</h3>
                            {% if help.has_next %}
                            <li class="page-item"><a class="page-link" href="?category={{ help_type }}&author={{ author }}&address={{ address }}&page={{ help.next_page_number }}">Next</a></li>
                            {% endif %}
                          </ul>
                    </div>
                </div>
              </div>
            {% endif %}
{% endblock %}